// TSX -> TS + HTML
// JSX => JS + HTML

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "ECommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}

// Sıfır bir nextjs projesi açıp 2 sayfalık kendinizi tanıtan bir websitesi geliştiriniz.
// 1- Ana sayfa
// 2- Projelerim sayfası

// API Çağrıları (Frontend)
// Dinamik Yapılar
// CSR - SSR
